trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - script: |
      echo "Python version:"
      python --version
    displayName: "Check Python Version"

  - script: |
      echo "Running hello world:"
      python helloworld.py
    displayName: "Run Python Code"
